### ISSUE TITLE
Page "Features" : "Cozy Pass" section

### ISSUE THREAD

**Issue by RichardFevrier** [cozy/cozy-site#166]
The section of the Cozy Pass feature is different from the sections above, it is a video.

It brings one caveat: you are not using the "encryption" term anywhere on your website.

It could seem strange to people to not see this kind of "technical" term (not just "secure") if they plan to give you their bank information and/or bills, receipts, passwords. What do you think?

**Comment by JF-Cozy** [comment]
First of all, thanks for your feedback, and sorry for the lack of response so far.

The page in question has since been redesigned, and we are indeed going to introduce this notion of security, which is very important to us.

Keep in touch :)
