### ISSUE TITLE
Dead link on the press kit

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-site#18]
I'm opening an issue (instead of a PR) as I don't know what is the right one, the press kit link on the Press page (https://github.com/cozy/cozy-site/blob/master/src/press.html#L43) seems to be dead.

**Comment by poupotte** [comment]
Thanks @babolivier for your report. @frankrousseau , @LucsT, @nledez  : Have you any news about tihs issue ?

**Comment by babolivier** [comment]
Just saw that the link was already fixed, I'm closing the issue :)

**Comment by frankrousseau** [comment]
Yep, thx!
