### ISSUE TITLE
Bad translation on comparaison page

### ISSUE THREAD

**Issue by martinsam** [cozy/cozy-site#26]
[http://cozy.io/fr/comparison/](http://cozy.io/fr/comparison/)

String : "comparison introduction two"

**Comment by frankrousseau** [comment]
Thx for reporting. I want to perform some update tonight. So, I'll fix it by that time.

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @martinsam for the report and @frankrousseau for the fix :+1:
