### ISSUE TITLE
Add a way to join our IRC channel

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-site#33]
A user reported tonight on IRC that he searched our site for the name of our IRC channel without being able to find it. He suggested having a full Contact page, with a link allowing to join our IRC channel with a web client.

**Comment by clochix** [comment]
Well, looking at the source code, I found the information, on the Community page. Maybe having a full contact page would make it easier to find.

**Comment by Aryess** [comment]
:+1:

**Comment by clochix** [comment]
There's still no mention on the website of our main support entry point, the IRC channel #cozycloud on freenode ☹
