### ISSUE TITLE
Instructions for VirtualBox installation are wrong

### ISSUE THREAD

**Issue by yurivict** [cozy/cozy-site#53]
Several problems:
- Bridge adapter with the engaged physical network card fails on my system, because that card is already open. You should not suggest bridging with any physical cards, because that is generally an impractical setup. You should suggest instructions how to forward a port from the VM to the host. The instructions for ssh and https forwarding are:

```
        VBoxManage modifyvm "cozy" --natpf1 "guestssh,tcp,,8022,,22"
        VBoxManage modifyvm "cozy" --natpf1 "guesthttps,tcp,,443,,443"
```

```
   I think you can ship the VM image with these instructions already applied in it.
```
- VM doesn't listen on the port 443, so https into it doesn't work. This makes the VM dysfunctional.

**Comment by clochix** [comment]
Thanks for reporting @yurivict ☺

@aeris is currently working on fixing some issues with the VirtualBox image, he will update the documentation once the image has been fixed.

**Comment by aeris** [comment]
Seems people use this image for easy setup on NAS or workstation, and not only for dev or test.
So the Cozy instance must be available on the LAN and accessible from any computer, not only the virtualbox host.

And first feedback on this image shows users are not very skilled ones and not comfortable with command line.
So this image must run out-of-the-box with minimal interaction.

Currently image state is not satisfying, we need out-of-the-box LAN accessible image (so bridged instance).
And only advanced users (dev/test) should have to modify image config for their uses.

**Comment by yurivict** [comment]
Bridging with physical NIC generally doesn't work for people just running it on the personal VBox. Setup in such case should be: 1. NAT 2. Port forward from localhost to VM 3. (possibly) Port forward from router to the host with VM. - This way it can be easily made available on the LAN and Internet.

It can be made LAN-accessible, just like I described above.

**Comment by aeris** [comment]
NAT with port forwarding is complicated to do out-of-the-box.

You need routing, ip forward, firewall configuration… on the host. If your virtualbox host is a NAS and you have to use GUI provided with it, you’re doomed without skills.
Most of our users with feedback have no enough network knowledge to achieve this correctly.

Current experience show bridging seems working easily, with Cozy visible as a standard and standalone machine on the LAN.
And with bridge, with avahi inside the image, users can directly access their cozy on `https://cozy.local/`, without having to look for IP address of the cozy (or host). Not possible with NAT.

Last, we know nothing on the virtualbox host, and NAT configuration is not context-free.
For example, on a NAS, all chances you have already running https and ssh servers, and so 443/22 redirections will fail or users have to access their cozy with differents ports, requiring more documentation or corner-case to handle. Bridging create a new clean machine on the LAN, so is far more context-free than NAT.

We need a virtualbox image working "as-is" in most of cases, requiring manual setup only if you have specific configuration (and so specific skills).
Better to have easy setup for beginner user and complex setup for advanced user than the opposite.

**Comment by clochix** [comment]
Hello @yurivict,

This Virtualbox image is now deprecated, it was for the previous version of Cozy which we don't maintain anymore.

For now, we have no short term plan to release an official image of the new Cozy for Virtualbox.

**Comment by yurivict** [comment]
What is the recommended way to run Cozy now then?

**Comment by clochix** [comment]
Hello @yurivict, 

We have published a few days ago Debian packages allowing to easily install the new Cozy on your own server: https://docs.cozy.io/en/install/debian/

We plan to also release an image for Raspberry Pi.

For now, we don't plan to provide official support for other platforms, but I'm sure our community will create Docker or VirtualBox images.

**Comment by yurivict** [comment]
Why can't Cozy be installed like any other project, under some install base like ```/use/local/cozy/```, keeping its DB in ex. ```/var/db/coze```? There are a lot of complex projects consisting of many executables that do just that.

**Comment by aeris** [comment]
This is the way we deliver the new v3 of Cozy. More Debian compliant.

Previous version was in NodeJS and depends of a lot of not officially Debian packaged third party components, which create a real difficulty to cleanly package it.
