### ISSUE TITLE
Weird image border on the home icon

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-site#8]
On the home icon there is a weird white overlay on the bottom corners of the dock (it looks like the home is on a music player dock).

Compare with the left icon and watch for the bottom corners:

![cozy-site-bug](https://cloud.githubusercontent.com/assets/3419050/11816609/88f8749c-a351-11e5-8ae1-bef0b7eb30bf.png)

**Comment by m4dz** [comment]
@kelukelu this one is for you :tongue:
